#!/usr/bin/python3

# run cht.sh
# Usage: cheat [query...]
# Example: cheat python print
# Example: cheat python print | less

import sys
import subprocess


def main():
    argv = sys.argv
    if len(argv) == 1:
        cmd1 = ["curl", "cht.sh/:list", "-s", "2>/dev/null"]
        cmd2 = ["fzf", "--preview", "'curl cht.sh/{} 2> /dev/null'",
                "--height", "40%",
                "--layout=reverse", "--border",
                "--preview-window=right:50%:wrap"]
        p1 = subprocess.Popen(cmd1, stdout=subprocess.PIPE)

        p2 = subprocess.Popen(cmd2, stdin=p1.stdout, stdout=subprocess.PIPE)

        p1.stdout.close()
        output = p2.communicate()[0]
        p1.wait()
        p2.wait()

        cmd3 = ["curl", "cht.sh/" + output.decode("utf-8").strip()]

        subprocess.run(cmd3)

        exit(0)
    if argv[1] == "-h":
        print("Usage: cheat [query...]")
        print("Example: cheat python print")
        exit(0)

    query = argv[1]
    for arg in argv[2:]:
        query = query + "/" + arg

    print("Query: " + query)
    subprocess.run(["curl", "cht.sh/" + query])


if __name__ == "__main__":
    main()
