#!/usr/bin/sh

# run cht.sh 
# Usage: cheat [query...]
# Example: cheat python print
# Example: cheat python print | less 



if [ $# -eq 0 ]; then
        curl cht.sh/:list 2>/dev/null | fzf --preview 'curl cht.sh/{} 2>/dev/null' \
                --height 40%  --layout=reverse --border --preview-window=right:50%:wrap \
                | xargs -r -I {} curl cht.sh/{} 2>/dev/null 
        exit 0 
fi

if [ "$1" = "-h" ]; then
        echo "Usage: cheat [query...]"
        echo "Example: cheat python print"

        exit 0
fi

query="$1"

for arg in "$@"; do
        if [ "$arg" != "$1" ]; then
                query="$query/$arg"
        fi
done

echo "Query: $query"
curl cht.sh/$query
